//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcResume.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEgitim
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "You can not skip it")]
        public string Baslik { get; set; }
        public string AltBaslik1 { get; set; }
        public string AltBaslik2 { get; set; }



        [StringLength(10, ErrorMessage ="Please enter 10 character")]
        public string GNO { get; set; }
        public string Tarih { get; set; }
    }
}
